remote_theme: pmarsceill/just-the-docs@v0.10.0

plugins:
  - jekyll-remote-theme

# Site settings
title: PiFire Documentation
description: Raspberry Pi Based Smoker Grill Controller
url: ""
baseurl: ""

# GitHub metadata
repository: nebhead/PiFire-Pages

# Just the Docs theme settings
search_enabled: true
heading_anchors: true

# Navigation structure
nav_sort: title

