remote_theme: clearpathrobotics/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme

# Site settings
title: PiFire Documentation
description: Raspberry Pi Based Smoker Grill Controller
url: ""
baseurl: ""

# GitHub metadata (optional - will be auto-filled in GitHub Actions)
repository: nebhead/PiFire-Pages

